# Generated by Django 2.2 on 2019-09-06 02:53

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FXTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='created')),
                ('kind', models.TextField()),
                ('payload', django.contrib.postgres.fields.jsonb.JSONField()),
                ('completed', models.DateTimeField(null=True)),
                ('completion_payload', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
            ],
        ),
    ]
